---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: pttg-ip-fm-audit-ui
  name: pttg-ip-fm-audit-ui
spec:
  ports:
  - name: https
    port: 443
    targetPort: 10443
  selector:
    name: pttg-ip-fm-audit-ui
